name: ArgentumcraftPVP
version: 1.0.0
description: A CTF-styled pvp mini game for the Argentumcraft server
authors: [austinv11, grandmind1]
website: argentumcraft.enjin.com
 
main: com.enjin.argentumcraft.ArgentumcraftPVP.ArgentumcraftPVP
commands:
   aPVPStart:
      description: Starts a pvp game.
      usage: /<command> <killsToWin>
      permission: APVP.startGame
      permission-message: You don't have permission
   
   aPVPStop:
      description: Stops a pvp game.
      usage: /<command>
      permission: APVP.stopGame
      permission-message: You don't have permission

   aPVPSetSpawn:
      description: Sets a spawn point for the desired team.
      usage: /<command> <red:blue>
      permission: APVP.setSpawn
      permission-message: You don't have permission

permissions:
   APVP.*:
        description: Gives access to all ArgentumcraftPVP related permissions
   APVP.startGame:
      description: Permission to start a pvp game.
   APVP.stopGame:
      description: Permission to stop a pvp game.
   APVP.setSpawn:
      description: Permission to set a spawn for a team.